[build]
  functions = "functions"
  publish = "/"

[[redirects]]
  from = "/loadscript/:id"
  to = "/.netlify/functions/pixelServe/:id"
  status = 200

[[redirects]]
  from = "/pixel"
  to = "/.netlify/functions/pixelServe"
  status = 200

[[redirects]]
  from = "/pixel/:id"
  to = "/.netlify/functions/pixelServe/:id"
  status = 200
