[build]
  functions = "functions"
  publish = "/"

# === Pixel Script Delivery ===
[[redirects]]
  from = "/pixel"
  to = "/.netlify/functions/pixelServe"
  status = 200
  force = true

[[redirects]]
  from = "/pixel/:id"
  to = "/.netlify/functions/pixelServe/:id"
  status = 200
  force = true

[[redirects]]
  from = "/loadscript/:id"
  to = "/.netlify/functions/pixelServe/:id"
  status = 200
  force = true

# === Tracking Endpoint ===
[[redirects]]
  from = "/track"
  to = "/.netlify/functions/track"
  status = 200
  force = true

# === Get Matching Ad ===
[[redirects]]
  from = "/getad"
  to = "/.netlify/functions/getAd"
  status = 200
  force = true

# === Click Redirect & Logging ===
[[redirects]]
  from = "/redirect"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
